### ISSUE TITLE
Search in Fleamarket after 3rd or 4th character typing - InventoryScreen not found Error

### ISSUE THREAD

**Issue by ViP3R76** [TadMaj/Tarkov-QuickSell#16]
![QuickSell_Error](https://github.com/user-attachments/assets/3170f8a7-33dd-4134-b463-055203344f0d)

This error occurs if you search on the left side in the fleamarket for an item. Example "Analgin", if you type at least "ana" it will throw this error in the lower right side. This happens at least for the minimum 3rd character and is repeatable.

**Comment by harmonyzt** [comment]
This occurs because binds for your Quick Sell to trader or flea actually pass no matter where you are in the menu, so it tries to find the stash screen and fails. So that's why when you type anything in flea market or name your gun preset this throws up.

The workaround for this could be instead of throwing an error just ignore the binds set when there's no InventoryScreen.
Here's where it happens:
https://github.com/TadMaj/Tarkov-QuickSell/blob/8111d478f40527b473a5954630b5622d1fea9122/Patches/ConfigController.cs#L81C1-L84C14
```C#
var target = GameObject.Find("InventoryScreen");
if (target == null)
{
   Utils.SendError("InventoryScreen not found");
}
```
